### ISSUE TITLE
Component creation - Error: spawn C:\WINDOWS\system32\cmd.exe ENOENT     at _errnoException (util.js:992:11)

### ISSUE THREAD

**Issue by peterennis** [ionic-team/create-stencil#11]
Error: spawn C:\WINDOWS\system32\cmd.exe ENOENT
    at _errnoException (util.js:992:11)

@manucorporat  How do I show what version of create-stencil is being used?

![capture385](https://user-images.githubusercontent.com/140737/44356433-32288000-a464-11e8-9a67-5ec1206ec440.png)

**Comment by rwaskiewicz** [comment]
Hey @peterennis 👋 

First and foremost, I apologize for how long it took for someone on the team to get back to you.  It seems like there _should_ be functionality to check the version of this CLI you're using, but I don't believe it's working at the moment.  I'm going to add a label to get this ingested into our backlog to be fixed.

**Comment by rwaskiewicz** [comment]
I'm unable to reproduce the issue in the latest version of create-stencil.

As of v3.0.2 of this CLI, the `--info` flag has been fixed, where folks can see the version of `create-stencil` they're on using `npm init stencil@latest -- --info`

As a result, I'm going to close this issue out.  If this is still an issue today, folks should feel free to open a new ticket. Thanks again!
