### ISSUE TITLE
ReferenceError: beep is not defined

### ISSUE THREAD

**Issue by otariidae** [ionic-team/create-stencil#13]
When I ran `npm init stencil` and pressed <kbd>↑</kbd>, I got this error.

```
? Pick a starter » - Use arrow-keys. Return to submit.

>  ionic-pwa     Everything you need to build fast, production ready PWAs
   app           Minimal starter for building a Stencil app or website
   component     Collection of web components that can be used anywherereadline.js:1032
            throw err;
            ^

ReferenceError: beep is not defined
    at SelectPrompt.bell (C:\Users\<username>\AppData\Roaming\npm-cache\_npx\1412\node_modules\create-stencil\dist\index.js:2:30265)
    at SelectPrompt.up (C:\Users\<username>\AppData\Roaming\npm-cache\_npx\1412\node_modules\create-stencil\dist\index.js:2:31832)
    at ReadStream.n (C:\Users\<username>\AppData\Roaming\npm-cache\_npx\1412\node_modules\create-stencil\dist\index.js:2:29953)
    at ReadStream.emit (events.js:182:13)
    at emitKeys (internal/readline.js:422:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (readline.js:1022:36)
    at ReadStream.emit (events.js:187:15)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
```
These lines seem to cause this error.
https://github.com/ionic-team/create-stencil/blob/80a4b8fa819b0d34c54bd0dd725e0a67c8df2c29/src/vendor/prompts/elements/prompt.js#L53-L55

OS: Windows10  
Node.js: v10.8.0  
npm: 6.2.0

**Comment by jthoms1** [comment]
This issue was fixed with commit b16ff543e2f8251c40bc481ad7f5a6a91a1a5ae8.

A new release as published to npm with the fix. Thanks!
