### ISSUE TITLE
npm init stencil not working

### ISSUE THREAD

**Issue by LiuZHolmes** [ionic-team/create-stencil#35]
When I run the init command and choose any of those options in promt it gave me:

Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1058:34)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket._finishInit (_tls_wrap.js:636:8)
Emitted 'error' event at:
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by wangchongchong1007** [comment]
Had a similar issue,how should i solve it.
