### ISSUE TITLE
[ ERROR ]  Cannot find module 'request' at Function.Module._resolveFilename

### ISSUE THREAD

**Issue by peterennis** [ionic-team/create-stencil#8]
@manucorporat 
Latest version.
Following instructions.

```
C:\ae\adaept.com\ionicons>npm list @stencil/core
@stencil/starter@0.0.1 C:\ae\adaept.com\ionicons
`-- @stencil/core@0.11.0


C:\ae\adaept.com\ionicons>
```

```
C:\ae\adaept.com>npm init stencil
npx: installed 1 in 2.407s
👋  Welcome to Stencil Create App!

   What kind of project do you want to create?

√ Pick a starter » 💎  app        (Minimal starter for building a Stencil app or website)
√ Project name ... ionicons

We are about to clone "ionic-team/stencil-app-starter" into "./ionicons"
√ Confirm? ... yes

 💎  Cloning ionic-team/stencil-app-starter...
 🏃‍  Changing directories...
 🔨  Preparing repo...
 📦  Installing packages...

 🎉  All done!

        cd ./ionicons
        npm start

Check out the docs: https://github.com/ionic-team/stencil-app-starter
```

```

C:\ae\adaept.com>cd ionicons

C:\ae\adaept.com\ionicons>npm start

> @stencil/starter@0.0.1 start C:\ae\adaept.com\ionicons
> stencil build --dev --watch --serve

[29:38.0]  @stencil/core v0.11.0
[29:38.0]  build, app, dev mode, started ...
[29:38.1]  transpile started ...
[29:40.4]  transpile finished in 2.27 s
[29:40.5]  module map started ...
[29:40.6]  generate styles started ...
[29:41.0]  compile global style start ...
[29:41.2]  compile global style finish in 224 ms
[29:41.2]  generate styles finished in 610 ms
[29:41.7]  module map finished in 1.20 s
[29:41.7]  generate bundles started ...
[29:41.7]  generate bundles finished in 12 ms
[29:41.7]  generate app files started ...
[29:43.7]  generate app files finished in 2.04 s

[ ERROR ]  Cannot find module 'request' at Function.Module._resolveFilename (module.js:547:15) at Function.Module._load
           (module.js:474:25) at Module.require (module.js:596:17) at require (internal/module.js:11:18) at
           C:\ae\adaept.com\ionicons\node_modules\request-promise-native\lib\rp.js:8:12 at module.exports
           (C:\ae\adaept.com\ionicons\node_modules\stealthy-require\lib\index.js:62:23) at Object.<anonymous>
           (C:\ae\adaept.com\ionicons\node_modules\request-promise-native\lib\rp.js:7:15) at Module._compile
           (module.js:652:30) at Object.Module._extensions..js (module.js:663:10) at Module.load (module.js:565:32)

[29:43.8]  dev server: http://localhost:3333/
Terminate batch job (Y/N)? y

C:\ae\adaept.com\ionicons>
```

![capture360](https://user-images.githubusercontent.com/140737/43505008-5954ae00-951a-11e8-8599-160fcd67540d.png)

**Comment by khaledosman** [comment]
I had the same issue, PS: this is only with the "app" starter, "ionic-pwa" works fine.
tl;dr run ```yarn && npm start``` to fix it.

```
MacBook-Pro-3:github khaledosman$ cd stencil-app/
MacBook-Pro-3:stencil-app khaledosman$ npm start

> @stencil/starter@0.0.1 start /Users/khaledosman/Documents/github/stencil-app
> stencil build --dev --watch --serve

[56:10.8]  @stencil/core v0.11.0 🍇
[56:10.8]  build, app, dev mode, started ...
[56:10.9]  transpile started ...
[56:12.3]  transpile finished in 1.45 s
[56:12.4]  module map started ...
[56:12.6]  generate styles started ...
[56:12.9]  compile global style start ...
[56:13.0]  compile global style finish in 148 ms
[56:13.0]  generate styles finished in 462 ms
[56:13.2]  module map finished in 898 ms
[56:13.2]  generate bundles started ...
[56:13.3]  generate bundles finished in 7 ms
[56:13.3]  generate app files started ...
[56:15.0]  generate app files finished in 1.72 s

[ ERROR ]  Cannot find module 'request' at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15) at
           Function.Module._load (internal/modules/cjs/loader.js:520:25) at Module.require
           (internal/modules/cjs/loader.js:650:17) at require (internal/modules/cjs/helpers.js:20:18) at
           /Users/khaledosman/Documents/github/stencil-app/node_modules/request-promise-native/lib/rp.js:8:12 at
           module.exports
           (/Users/khaledosman/Documents/github/stencil-app/node_modules/stealthy-require/lib/index.js:62:23) at
           Object.<anonymous>
           (/Users/khaledosman/Documents/github/stencil-app/node_modules/request-promise-native/lib/rp.js:7:15) at
           Module._compile (internal/modules/cjs/loader.js:702:30) at Object.Module._extensions..js
           (internal/modules/cjs/loader.js:713:10) at Module.load (internal/modules/cjs/loader.js:612:32)

[56:15.0]  dev server: http://localhost:3333/
```
I tried to manually do an npm install, but I got a bunch of errors.. so I did a yarn install instead and that worked fine
```
MacBook-Pro-3:stencil-app khaledosman$ npm install

> fsevents@1.1.2 install /Users/khaledosman/Documents/github/stencil-app/node_modules/fsevents
> node install

node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@10.5.0 (node-v64 ABI) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@10.5.0 (node-v64 ABI) (falling back to source compile with node-gyp)
  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:10:
In file included from /System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:43:
In file included from /System/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:72:
/usr/local/include/Block.h:16:3: error: Never include this file directly. Use <lzma.h> instead.
#       error Never include this file directly. Use <lzma.h> instead.
        ^
In file included from ../fsevents.cc:10:
In file included from /System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:43:
In file included from /System/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:72:
/usr/local/include/Block.h:16:3: error: Never include this file directly. Use <lzma.h> instead.
#       error Never include this file directly. Use <lzma.h> instead.
        ^
/usr/local/include/Block.h:93:2: error: unknown type name 'lzma_check'
        lzma_check check;
        ^
/usr/local/include/Block.h:148:2: error: unknown type/usr/local/include/Block.h:93: 2:name  'lzma_vli'error
: unknown type name 'lzma_check'
        lzma_vli compressed_size;
        ^
        lzma_check check;
        ^
/usr/local/include/Block.h:148:2: error: unknown type name 'lzma_vli'
        lzma_vli compressed_size;
        ^
/usr/local/include/Block.h:172:2: error: unknown type name 'lzma_vli'
        lzma_vli uncompressed_size;
        ^
/usr/local/include/Block.h:172:2: error: unknown type name 'lzma_vli'
        lzma_vli uncompressed_size;
        ^
/usr/local/include/Block.h:200:2: error: unknown type name 'lzma_filter'
        lzma_filter *filters;
        ^
/usr/local/include/Block.h:200:2: error: unknown type name 'lzma_filter'
        lzma_filter *filters;
        ^
/usr/local/include/Block.h:217:20: error: use of undeclared identifier 'LZMA_CHECK_SIZE_MAX'
        uint8_t raw_check[LZMA_CHECK_SIZE_MAX];
                          ^
/usr/local/include/Block.h:217:20: error: use of undeclared identifier 'LZMA_CHECK_SIZE_MAX'
        uint8_t raw_check[LZMA_CHECK_SIZE_MAX];
                          ^
/usr/local/include/Block.h:231:2: error: unknown type name 'lzma_vli'
        lzma_vli reserved_int3;
        ^
/usr/local/include/Block.h:231:2: error: unknown type name 'lzma_vli'
        lzma_vli reserved_int3;
        ^
/usr/local/include/Block.h:232:2: error: unknown type name 'lzma_vli'
        lzma_vli reserved_int4;
        ^
/usr/local/include/Block.h:232:2: error: unknown type name 'lzma_vli'
        lzma_vli reserved_int4;
        ^
/usr/local/include/Block.h:233:2: error: unknown type name 'lzma_vli'
        lzma_vli reserved_int5;
        ^
/usr/local/include/Block.h:233:2: error: unknown type name 'lzma_vli'
        lzma_vli reserved_int5;
        ^
/usr/local/include/Block.h:234:2: error: unknown type name 'lzma_vli'
        lzma_vli reserved_int6;
        ^
/usr/local/include/Block.h:234:2: error: unknown type name 'lzma_vli'
        lzma_vli reserved_int6;
        ^
/usr/local/include/Block.h:235:2: error: unknown type name 'lzma_vli'
        lzma_vli reserved_int7;
        ^
/usr/local/include/Block.h:235:2: error: unknown type name 'lzma_vli'
        lzma_vli reserved_int7;
        ^
/usr/local/include/Block.h:236:2: error: unknown type name 'lzma_vli'
        lzma_vli reserved_int8;
        ^
/usr/local/include/Block.h:236:2: error: unknown type name 'lzma_vli'
        lzma_vli reserved_int8;
        ^
/usr/local/include/Block.h:237:2: error: unknown type name 'lzma_reserved_enum'
        lzma_reserved_enum reserved_enum1;
        ^
/usr/local/include/Block.h:237:2: error: unknown type name 'lzma_reserved_enum'
        lzma_reserved_enum reserved_enum1;
        ^
/usr/local/include/Block.h:238:2: error: unknown type name 'lzma_reserved_enum'
        lzma_reserved_enum reserved_enum2;
        ^
/usr/local/include/Block.h:238:2: error: unknown type name 'lzma_reserved_enum'
        lzma_reserved_enum reserved_enum2;
        ^
/usr/local/include/Block.h:239:2: error: unknown type name 'lzma_reserved_enum'
        lzma_reserved_enum reserved_enum3;
        ^
/usr/local/include/Block.h:239:2: error: unknown type name 'lzma_reserved_enum'
        lzma_reserved_enum reserved_enum3;
        ^
/usr/local/include/Block.h:240:2: error: unknown type name 'lzma_reserved_enum'
        lzma_reserved_enum reserved_enum4;
        ^
/usr/local/include/Block.h:261:2: error: unknown type name 'lzma_bool'
        lzma_bool ignore_check;
        ^
/usr/local/include/Block.h:240:2: error: unknown type name 'lzma_reserved_enum'
        lzma_reserved_enum reserved_enum4;
        ^
/usr/local/include/Block.h:263:2: error: unknown type name 'lzma_bool'
        lzma_bool reserved_bool2;
        ^
/usr/local/include/Block.h:261:2: error: unknown type name 'lzma_bool'
        lzma_bool ignore_check;
        ^
/usr/local/include/Block.h:264:2: error: unknown type name 'lzma_bool'
/usr/local/include/Block.h:263:2: error: unknown type name 'lzma_bool'
        lzma_bool reserved_bool2;
        ^
        lzma_bool reserved_bool3;
        ^
/usr/local/include/Block.h:264:2: error: unknown type name 'lzma_bool'
        lzma_bool reserved_bool3;
        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
20 errors generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/khaledosman/Documents/github/stencil-app/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/khaledosman/Documents/github/stencil-app/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64"
gyp ERR! make: cwd*** [Release/obj.target/fse/fsevents.o] Error 1
 /Users/khaledosman/Documents/github/stencil-app/node_modules/fsevents
gyp ERR! node -v v10.5.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
node-pre-gyp ERR!gyp  build error
ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/khaledosman/Documents/github/stencil-app/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/khaledosman/Documents/github/stencil-app/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64"
gypnode-pre-gyp  ERR!ERR! cwd  /Users/khaledosman/Documents/github/stencil-app/node_modules/fsevents
stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/khaledosman/Documents/github/stencil-app/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/khaledosman/Documents/github/stencil-app/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
gyp node-pre-gypERR!  ERR!node -v  v10.5.0
stack     at ChildProcess.<anonymous> (/Users/khaledosman/Documents/github/stencil-app/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
gyp node-pre-gyp ERR!ERR!  node-gyp -v v3.8.0
stack     at ChildProcess.emit (events.js:182:13)
node-pre-gypgyp  ERR!ERR!  stacknot ok     at maybeClose (internal/child_process.js:961:16)

node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/khaledosman/Documents/github/stencil-app/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/khaledosman/Documents/github/stencil-app/node_modules/fsevents
node-pre-gyp ERR! node -v v10.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/khaledosman/Documents/github/stencil-app/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/khaledosman/Documents/github/stencil-app/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
npm WARN request-promise-core@1.1.1 requires a peer of request@^2.34 but none is installed. You must install peer dependencies yourself.
npm WARN request-promise-native@1.0.5 requires a peer of request@^2.34 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

audited 24968 packages in 10.356s
found 366 vulnerabilities (361 low, 5 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by seanwuapps** [comment]
for me after running `npm update` the error went away.

**Comment by virani1981** [comment]
cd into project folder and run npm update
this updated to version 0.11.4 and solved the issue

**Comment by rwaskiewicz** [comment]
👋 

I apologize for the amount of time it took to get to this issue! This appears to be solved in the latest version of `create-stencil` (v2.0.0) and `stencil/core` (v2.13.0).

I'm going to close this issue, but I encourage anyone seeing this still to please open a new issue.

Thanks again!
